
from typing import Literal, get_args

from src.data_processing.emoji_processing import remove_emojis

CountryFlag = Literal[
    "🇦🇩Andorra",
    "🇦🇪United Arab Emirates",
    "🇦🇫Afghanistan",
    "🇦🇬Antigua and Barbuda",
    "🇦🇱Albania",
    "🇦🇲Armenia",
    "🇦🇴Angola",
    "🇦🇷Argentina",
    "🇦🇹Austria",
    "🇦🇺Australia",
    "🇦🇿Azerbaijan",
    "🇧🇦Bosnia and Herzegovina",
    "🇧🇧Barbados",
    "🇧🇩Bangladesh",
    "🇧🇪Belgium",
    "🇧🇫Burkina Faso",
    "🇧🇬Bulgaria",
    "🇧🇭Bahrain",
    "🇧🇮Burundi",
    "🇧🇯Benin",
    "🇧🇳Brunei",
    "🇧🇴Bolivia",
    "🇧🇷Brazil",
    "🇧🇸Bahamas",
    "🇧🇹Bhutan",
    "🇧🇼Botswana",
    "🇧🇾Belarus",
    "🇧🇿Belize",
    "🇨🇦Canada",
    "🇨🇩Democratic Republic of the Congo",
    "🇨🇫Central African Republic",
    "🇨🇬Republic of the Congo",
    "🇨🇭Switzerland",
    "🇨🇮Côte d'Ivoire",
    "🇨🇰Cook Islands",
    "🇨🇱Chile",
    "🇨🇲Cameroon",
    "🇨🇳China",
    "🇨🇴Colombia",
    "🇨🇷Costa Rica",
    "🇨🇺Cuba",
    "🇨🇻Cape Verde",
    "🇨🇾Cyprus",
    "🇨🇿Czech Republic",
    "🇩🇪Germany",
    "🇩🇯Djibouti",
    "🇩🇰Denmark",
    "🇩🇴Dominican Republic",
    "🇩🇿Algeria",
    "🇪🇨Ecuador",
    "🇪🇪Estonia",
    "🇪🇬Egypt",
    "🇪🇷Eritrea",
    "🇪🇸Spain",
    "🇪🇹Ethiopia",
    "🇫🇮Finland",
    "🇫🇯Fiji",
    "🇫🇲Micronesia",
    "🇫🇷France",
    "🇬🇦Gabon",
    "🇬🇧United Kingdom",
    "🇬🇩Grenada",
    "🇬🇪Georgia",
    "🇬🇭Ghana",
    "🇬🇷Greece",
    "🇬🇹Guatemala",
    "🇬🇳Guinea",
    "🇬🇼Guinea-Bissau",
    "🇬🇾Guyana",
    "🇭🇳Honduras",
    "🇭🇷Croatia",
    "🇭🇹Haiti",
    "🇭🇺Hungary",
    "🇮🇩Indonesia",
    "🇮🇪Ireland",
    "🇮🇱Israel",
    "🇮🇳India",
    "🇮🇶Iraq",
    "🇮🇷Iran",
    "🇮🇸Iceland",
    "🇮🇹Italy",
    "🇯🇲Jamaica",
    "🇯🇴Jordan",
    "🇯🇵Japan",
    "🇰🇪Kenya",
    "🇰🇬Kyrgyzstan",
    "🇰🇭Cambodia",
    "🇰🇮Kiribati",
    "🇰🇲Comoros",
    "🇰🇳Saint Kitts and Nevis",
    "🇰🇵North Korea",
    "🇰🇷South Korea",
    "🇰🇼Kuwait",
    "🇰🇿Kazakhstan",
    "🇱🇦Laos",
    "🇱🇧Lebanon",
    "🇱🇨Saint Lucia",
    "🇱🇮Liechtenstein",
    "🇱🇰Sri Lanka",
    "🇱🇷Liberia",
    "🇱🇸Lesotho",
    "🇱🇹Lithuania",
    "🇱🇺Luxembourg",
    "🇱🇻Latvia",
    "🇱🇾Libya",
    "🇲🇦Morocco",
    "🇲🇨Monaco",
    "🇲🇩Moldova",
    "🇲🇪Montenegro",
    "🇲🇬Madagascar",
    "🇲🇭Marshall Islands",
    "🇲🇰North Macedonia",
    "🇲🇱Mali",
    "🇲🇲Myanmar",
    "🇲🇳Mongolia",
    "🇲🇪Montenegro",
    "🇲🇿Mozambique",
    "🇲🇽Mexico",
    "🇲🇹Malta",
    "🇳🇦Namibia",
    "🇳🇪Niger",
    "🇳🇬Nigeria",
    "🇳🇮Nicaragua",
    "🇳🇱Netherlands",
    "🇳🇴Norway",
    "🇳🇵Nepal",
    "🇳🇿New Zealand",
    "🇴🇲Oman",
    "🇵🇦Panama",
    "🇵🇪Peru",
    "🇵🇭Philippines",
    "🇵🇰Pakistan",
    "🇵🇱Poland",
    "🇵🇹Portugal",
    "🇵🇼Palau",
    "🇵🇾Paraguay",
    "🇶🇦Qatar",
    "🇷🇴Romania",
    "🇷🇸Serbia",
    "🇷🇺Russia",
    "🇷🇼Rwanda",
    "🇸🇦Saudi Arabia",
    "🇸🇧Solomon Islands",
    "🇸🇨Seychelles",
    "🇸🇩Sudan",
    "🇸🇪Sweden",
    "🇸🇬Singapore",
    "🇸🇮Slovenia",
    "🇸🇰Slovakia",
    "🇸🇱Sierra Leone",
    "🇸🇲San Marino",
    "🇸🇳Senegal",
    "🇸🇴Somalia",
    "🇸🇷Suriname",
    "🇸🇸South Sudan",
    "🇸🇹São Tomé and Príncipe",
    "🇸🇻El Salvador",
    "🇸🇾Syria",
    "🇸🇿Eswatini",
    "🇹🇯Tajikistan",
    "🇹🇭Thailand",
    "🇹🇬Togo",
    "🇹🇳Tunisia",
    "🇹🇲Turkmenistan",
    "🇹🇱East Timor",
    "🇹🇷Turkey",
    "🇹🇹Trinidad and Tobago",
    "🇹🇻Tuvalu",
    "🇺🇦Ukraine",
    "🇺🇬Uganda",
    "🇺🇸United States",
    "🇺🇾Uruguay",
    "🇺🇿Uzbekistan",
    "🇻🇦Vatican City",
    "🇻🇨Saint Vincent and the Grenadines",
    "🇻🇪Venezuela",
    "🇻🇳Vietnam",
    "🇻🇺Vanuatu",
    "🇼🇸Samoa",
    "🇾🇪Yemen",
    "🇿🇦South Africa",
    "🇿🇲Zambia",
    "🇿🇼Zimbabwe",
    "❓UNKNOWN COUNTRY",
    "NO COUNTRY FOUND"
]



country_names_list = [remove_emojis(country) for country in get_args(CountryFlag) if not "COUNTRY" in country]
country_names_with_not_list = [f"NOT {country}" for country in country_names_list if not "COUNTRY" in country]
country_names_list.extend(country_names_with_not_list)
country_names_list.extend(["European Union", "Remote"])
VacancyLocation = Literal[*country_names_list]

if __name__ == "__main__":
    countries_list = get_args(CountryFlag)
    print(len(countries_list))
    countries_list = get_args(VacancyLocation)
    print(len(countries_list))



